apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyeeerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyeeerr
  template:
    metadata:
      labels:
        app: hyeeerr
    spec:
      containers:
      - image: okteto.dev/hyeeerr:latest
        name: hyeeerr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "390b3fa8-b922-4218-ae4d-5bf21e7de4da"
        - name: Vless_Path
          value: "/vl5ddd55"
        - name: Vmess_UUID
          value: "390b3fa8-b922-4218-ae4d-5bf21e7de4da"
        - name: Vmess_Path
          value: "/vm6xsa66"
        - name: Share_Path
          value: "/v2link"
